In [3]:
# Topic 1: concat()-it is used to combine two or more DataFrames.

In [4]:
import pandas as pd

In [5]:
orders = pd.read_csv("/content/drive/MyDrive/Orders.csv")
products = pd.read_csv("/content/drive/MyDrive/Products.csv")
customers = pd.read_csv("/content/drive/MyDrive/Customers.csv")

In [6]:
print("Orders:")
display(orders.head())
print("Products:")
display(products.head())
print("Customers:")
display(customers.head())

Orders:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

Products:

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

Customers:

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

In [7]:
print("Orders shape:", orders.shape)
print("Products shape:", products.shape)
print("Customers shape:", customers.shape)

Orders shape: (120, 7)
Products shape: (20, 5)
Customers shape: (30, 5)

In [8]:
# In Pandas, concat is used to combine DataFrames along an axis.

In [9]:
orders_part1 = orders.iloc[:60]
orders_part2 = orders.iloc[60:]

In [10]:
print("Part 1:", orders_part1.shape)
print("Part 2:", orders_part2.shape)

Part 1: (60, 7)
Part 2: (60, 7)

In [11]:
orders_combined = pd.concat(
    [orders_part1, orders_part2]
)

In [12]:
# here we concatinated both parts of orders dataset

In [13]:
display(orders_combined.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [14]:
# concatinating with the help of axis
# axis=0 -> its default , it means its concatenating rows
# axis=0 is vertical/row wise stacking

In [15]:
orders_combined = pd.concat(
    [orders_part1, orders_part2],
    axis=0
)

In [16]:
orders_combined.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [17]:
orders_combined.tail()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled

In [18]:
# ignore_index=True -> Ignore the existing indexes of the input DataFrames and create a new continuous index.

In [19]:
orders_part1=orders.iloc[:60].copy()
orders_part2=orders.iloc[60:].copy()

orders_combined = pd.concat(
    [orders_part1,orders_part2],
    axis=0,
    ignore_index=True
)
print("Original Orders shape: ", orders.shape)
print("part 1 shape:", orders_part1.shape)
print("part 2 shape:", orders_part2.shape)
print("Combined Orders shape:", orders_combined.shape)

Original Orders shape:  (120, 7)
part 1 shape: (60, 7)
part 2 shape: (60, 7)
Combined Orders shape: (120, 7)

In [20]:
#axis=0 vs axis=1

In [21]:
# axis=0 — rows
pd.concat([orders_part1, orders_part2],
          axis=0
          )

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered
...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled

In [22]:
# axis=1 — column-wise / horizontal concatenation

In [23]:
# Select the first three columns from the Orders DataFrame
orders_columns_part1 = orders.iloc[:, :3]

In [24]:
# Select the remaining columns from the Orders DataFrame
orders_columns_part2 = orders.iloc[:, 3:]

In [25]:
#Concatenate them horizontally

In [26]:
orders_com=pd.concat(
    [orders_columns_part1, orders_columns_part2],
    axis=1
)

In [27]:
display(orders_com.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [28]:
# Compare the original and reconstructed DataFrame shapes
print("Original Orders shape:", orders.shape)
print("Reconstructed shape:", orders_com.shape)

Original Orders shape: (120, 7)
Reconstructed shape: (120, 7)

In [29]:
# Topic 2 — merge()
# merge() is used to join two DataFrames using one or more common columns.

In [30]:
# Display the column names available in the Orders DataFrame
print("Orders columns:")
print(orders.columns.tolist())

# Display the column names available in the Customers DataFrame
print("\nCustomers columns:")
print(customers.columns.tolist())

# Display the column names available in the Products DataFrame
print("\nProducts columns:")
print(products.columns.tolist())

Orders columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']

Customers columns:
['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type']

Products columns:
['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

In [31]:
display(orders.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [ ]:
# it Display the first five rows of the Orders DataFrame

In [32]:
display(customers.head())

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

In [ ]:
# it Display the first five rows of the Customers DataFrame

In [33]:
display(products.head())

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

In [ ]:
# it Display the first five rows of the Products DataFrame

In [35]:
orders_customers=pd.merge(
    orders,
    customers,
    on="Customer_ID"
)

In [ ]:
# orders_customers is the new DataFrame containing information from both datasets.
# Used Customer_ID as the common column to match rows between the two DataFrames.

In [36]:
display(orders_customers.head())
# Display the first five rows after merging Orders and Customers

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

In [37]:
# Display the shape of the merged DataFrame
print("Orders shape:", orders.shape)
print("Customers shape:", customers.shape)
print("Orders + Customers shape:", orders_customers.shape)

Orders shape: (120, 7)
Customers shape: (30, 5)
Orders + Customers shape: (120, 11)

In [38]:
# Display the column names of the merged DataFrame
print(orders_customers.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type']

In [40]:
orders_customers=pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="inner"
)
# An inner join keeps only records where the key exists in both DataFrames.

In [42]:
# Keep only matching Customer_ID values from both DataFrames
orders_customers_inner = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="inner"
)
orders_customers_inner

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,Reyansh Jain,Kolkata,East,New
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,Yusuf Dar,Srinagar,North,New
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular

In [ ]:
# Left Join

In [43]:
# Keep all Orders and add matching Customer information where available
orders_customers_left = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

In [44]:
orders_customers_left

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,Reyansh Jain,Kolkata,East,New
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,Yusuf Dar,Srinagar,North,New
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular

In [47]:
# Keep all Customers and add matching Order information where available
orders_customers_right = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="right"
)
orders_customers_right
# keeps all customers

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0106,2026-01-02,C001,P009,1,Net Banking,Delivered,Aarav Sharma,Srinagar,North,Premium
1,O0111,2026-03-14,C001,P001,4,Debit Card,Delivered,Aarav Sharma,Srinagar,North,Premium
2,O0027,2026-01-11,C002,P008,1,Cash on Delivery,Shipped,Zoya Khan,Delhi,North,Regular
3,O0091,2026-01-01,C002,P011,2,Credit Card,Delivered,Zoya Khan,Delhi,North,Regular
4,O0096,2026-02-07,C002,P013,1,Net Banking,Shipped,Zoya Khan,Delhi,North,Regular
...,...,...,...,...,...,...,...,...,...,...,...
115,O0072,2026-03-21,C029,P009,4,Net Banking,Cancelled,Sameer Qureshi,Jammu,North,New
116,O0073,2026-03-02,C029,P004,3,Debit Card,Cancelled,Sameer Qureshi,Jammu,North,New
117,O0078,2026-02-17,C029,P004,5,Cash on Delivery,Delivered,Sameer Qureshi,Jammu,North,New
118,O0024,2026-02-20,C030,P001,4,Net Banking,Delivered,Riya Kapoor,Bengaluru,South,Premium
119,O0063,2026-02-25,C030,P020,3,Credit Card,Shipped,Riya Kapoor,Bengaluru,South,Premium

In [ ]:
# Outer Join

In [49]:
# Keep all records from both Orders and Customers
orders_customers_outer = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="outer"
)
orders_customers_outer

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0106,2026-01-02,C001,P009,1,Net Banking,Delivered,Aarav Sharma,Srinagar,North,Premium
1,O0111,2026-03-14,C001,P001,4,Debit Card,Delivered,Aarav Sharma,Srinagar,North,Premium
2,O0027,2026-01-11,C002,P008,1,Cash on Delivery,Shipped,Zoya Khan,Delhi,North,Regular
3,O0091,2026-01-01,C002,P011,2,Credit Card,Delivered,Zoya Khan,Delhi,North,Regular
4,O0096,2026-02-07,C002,P013,1,Net Banking,Shipped,Zoya Khan,Delhi,North,Regular
...,...,...,...,...,...,...,...,...,...,...,...
115,O0072,2026-03-21,C029,P009,4,Net Banking,Cancelled,Sameer Qureshi,Jammu,North,New
116,O0073,2026-03-02,C029,P004,3,Debit Card,Cancelled,Sameer Qureshi,Jammu,North,New
117,O0078,2026-02-17,C029,P004,5,Cash on Delivery,Delivered,Sameer Qureshi,Jammu,North,New
118,O0024,2026-02-20,C030,P001,4,Net Banking,Delivered,Riya Kapoor,Bengaluru,South,Premium
119,O0063,2026-02-25,C030,P020,3,Credit Card,Shipped,Riya Kapoor,Bengaluru,South,Premium

In [50]:
# Merge Orders with Customers using Customer_ID
# A left join keeps every order and adds matching customer information
orders_customers = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

In [51]:
# Display the first five rows of the merged DataFrame
display(orders_customers.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

In [52]:
# Check the shape after merging Orders and Customers
print("Orders shape:", orders.shape)
print("Orders + Customers shape:", orders_customers.shape)

Orders shape: (120, 7)
Orders + Customers shape: (120, 11)

In [53]:
# Merge the Orders + Customers DataFrame with Products
# Product_ID is used as the common key
# A left join keeps every order
processed = pd.merge(
    orders_customers,
    products,
    on="Product_ID",
    how="left"
)

In [54]:
# Display the first five rows of the final merged DataFrame
display(processed.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

In [56]:
# Display the shape after adding product information
print("Orders + Customers + Products shape:", processed.shape)

Orders + Customers + Products shape: (120, 15)

In [55]:
# Display all columns in the final merged DataFrame
print(processed.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

In [57]:
# Create the first half of the Orders DataFrame
orders_part1 = orders.iloc[:60].copy()

# Create the second half of the Orders DataFrame
orders_part2 = orders.iloc[60:].copy()

# Combine both parts vertically using concat()
# axis=0 means rows are combined vertically
# ignore_index=True creates a new continuous index
orders_combined = pd.concat(
    [orders_part1, orders_part2],
    axis=0,
    ignore_index=True
)
# Display the shapes to verify the concatenation
print("Original Orders shape:", orders.shape)
print("First part shape:", orders_part1.shape)
print("Second part shape:", orders_part2.shape)
print("Combined Orders shape:", orders_combined.shape)

Original Orders shape: (120, 7)
First part shape: (60, 7)
Second part shape: (60, 7)
Combined Orders shape: (120, 7)

In [58]:
# Display the first five rows of the combined Orders DataFrame
display(orders_combined.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [59]:
# Merge Orders with Customers
# Merge Orders with Customers using Customer_ID
# A left join keeps all order records and adds matching customer information
orders_customers = pd.merge(
    orders_combined,
    customers,
    on="Customer_ID",
    how="left"
)

In [60]:
# Display the first five rows after merging Orders and Customers
display(orders_customers.head())

# Display the shape of the merged DataFrame
print("Orders shape:", orders_combined.shape)
print("Orders + Customers shape:", orders_customers.shape)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

Orders shape: (120, 7)
Orders + Customers shape: (120, 11)

In [ ]:
# Merge with Products

In [61]:
# Merge the Orders + Customers DataFrame with the Products dataset
# Product_ID is used as the common key
# A left join keeps all order records
processed = pd.merge(
    orders_customers,
    products,
    on="Product_ID",
    how="left"
)

In [62]:
# Display the first five rows of the fully merged DataFrame
display(processed.head())

# Display the shape of the final merged DataFrame
print("Final merged shape:", processed.shape)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

Final merged shape: (120, 15)

In [63]:
# Display all columns available after merging the three datasets
print(processed.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

In [ ]:
# Convert Order_Date to DateTime

In [64]:
processed["Order_Date"]=pd.to_datetime(processed['Order_Date'])

In [65]:
print(processed["Order_Date"].dtype)

datetime64[ns]

In [ ]:
# Extract Year

In [74]:
# Extract the year from Order_Date and create a new column
processed["Order_Year"]=processed["Order_Date"].dt.year

In [ ]:
# Extract Month

In [68]:
# Extract the month number from Order_Date
processed["Order_Month"]=processed["Order_Date"].dt.month

In [ ]:
# Extract Month Name

In [69]:
# Extract the month name from Order_Date
processed["Order_Month_Name"] = processed["Order_Date"].dt.month_name()

In [71]:
# Extract Day
processed["Order_Day"] = processed["Order_Date"].dt.day

In [72]:
# Extract the day name such as Monday, Tuesday, etc.
processed["Order_Day_Name"] = processed["Order_Date"].dt.day_name()

In [75]:
# Display the original date and all newly extracted date information
display(
    processed[
        [
            "Order_Date",
            "Order_Year",
            "Order_Month",
            "Order_Month_Name",
            "Order_Day",
            "Order_Day_Name"
        ]
    ].head(10)
)

,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name
0,2026-02-19,2026,2,February,19,Thursday
1,2026-01-25,2026,1,January,25,Sunday
2,2026-02-26,2026,2,February,26,Thursday
3,2026-03-04,2026,3,March,4,Wednesday
4,2026-03-29,2026,3,March,29,Sunday
5,2026-02-09,2026,2,February,9,Monday
6,2026-02-10,2026,2,February,10,Tuesday
7,2026-03-27,2026,3,March,27,Friday
8,2026-03-13,2026,3,March,13,Friday
9,2026-03-05,2026,3,March,5,Thursday

In [ ]:
# Use apply() to Calculate Total Amount

In [ ]:
# Total Amount = Unit Price × Quantity

In [76]:
# Calculate the total value of each order
# The function is applied row-wise using axis=1
processed["Total_Amount"] = processed.apply(
    lambda row: row["Unit_Price"] * row["Quantity"],
    axis=1
)

In [77]:
display(
    processed["Total_Amount"]
)

0       4998
1       1798
2       3299
3       2997
4      17495
       ...
115     1499
116     2997
117     2396
118     4998
119     1999
Name: Total_Amount, Length: 120, dtype: int64

In [78]:
display(
    processed[
        [
            "Product_Name",
            "Unit_Price",
            "Quantity",
            "Total_Amount"
        ]
    ].head(10)
)

              Product_Name  Unit_Price  Quantity  Total_Amount
0              Cricket Bat        2499         2          4998
1           Wireless Mouse         899         2          1798
2              Smart Watch        3299         1          3299
3  Machine Learning Basics         999         3          2997
4             Coffee Maker        3499         5         17495
5                 Football         799         3          2397
6           Wireless Mouse         899         3          2697
7               Power Bank        1199         4          4796
8             Coffee Maker        3499         2          6998
9               Power Bank        1199         2          2398

In [80]:
# Create an order-value category based on Total_Amount
# apply() is used to transform each Total_Amount value
processed["Order_Value_Category"] = processed["Total_Amount"].apply(
    lambda amount:
        "High" if amount >= 5000
        else "Medium" if amount >= 2000
        else "Low" if amount >=1000
    else "Very low"
)

In [81]:
# Display the total amount and its corresponding category
display(
    processed[
        [
            "Total_Amount",
            "Order_Value_Category"
        ]
    ].head(10)
)

   Total_Amount Order_Value_Category
0          4998               Medium
1          1798                  Low
2          3299               Medium
3          2997               Medium
4         17495                 High
5          2397               Medium
6          2697               Medium
7          4796               Medium
8          6998                 High
9          2398               Medium

In [ ]:
# Right now our DataFrame contains all the information, but we should arrange the columns in a meaningful order.

In [82]:
# Define the final column order for the processed dataset
final_columns = [
    "Order_ID",
    "Order_Date",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day",
    "Order_Day_Name",

    "Customer_ID",
    "Customer_Name",
    "City",
    "Region",
    "Membership_Type",

    "Product_ID",
    "Product_Name",
    "Category",
    "Brand",
    "Unit_Price",

    "Quantity",
    "Total_Amount",
    "Order_Value_Category",

    "Payment_Method",
    "Order_Status"
]

# Select the columns in the required order
processed = processed[final_columns]

In [83]:
# Sort the processed dataset by Order_Date
# reset_index() creates a clean index after sorting
processed=processed.sort_values(
    "Order_Date"
).reset_index(drop=True)

In [ ]:
# View the Final Dataset

In [84]:
display(processed.head(10))

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name,Customer_ID,Customer_Name,City,...,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Total_Amount,Order_Value_Category,Payment_Method,Order_Status
0,O0051,2026-01-01,2026,1,January,1,Thursday,C008,Sara Ahmed,Hyderabad,...,P017,Yoga Mat,Sports,FitLife,899,4,3596,Medium,Net Banking,Delivered
1,O0091,2026-01-01,2026,1,January,1,Thursday,C002,Zoya Khan,Delhi,...,P011,Air Fryer,Home & Kitchen,CookSmart,4999,2,9998,High,Credit Card,Delivered
2,O0022,2026-01-02,2026,1,January,2,Friday,C023,Nikhil Sood,Chandigarh,...,P014,Data Science Handbook,Books,DataPress,899,4,3596,Medium,Net Banking,Delivered
3,O0106,2026-01-02,2026,1,January,2,Friday,C001,Aarav Sharma,Srinagar,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,1,3499,Medium,Net Banking,Delivered
4,O0076,2026-01-03,2026,1,January,3,Saturday,C019,Yusuf Dar,Srinagar,...,P015,Machine Learning Basics,Books,AIPress,999,1,999,Very low,Debit Card,Delivered
5,O0108,2026-01-04,2026,1,January,4,Sunday,C006,Ishita Gupta,Bengaluru,...,P020,Dumbbell Set,Sports,StrongFit,1999,1,1999,Low,Net Banking,Delivered
6,O0041,2026-01-04,2026,1,January,4,Sunday,C008,Sara Ahmed,Hyderabad,...,P012,Water Bottle,Home & Kitchen,HydroLife,699,5,3495,Medium,Cash on Delivery,Delivered
7,O0018,2026-01-05,2026,1,January,5,Monday,C003,Rohan Mehta,Mumbai,...,P011,Air Fryer,Home & Kitchen,CookSmart,4999,4,19996,High,Net Banking,Cancelled
8,O0104,2026-01-05,2026,1,January,5,Monday,C011,Vivaan Kapoor,Jaipur,...,P006,Hoodie,Clothing,UrbanWear,1599,3,4797,Medium,Debit Card,Shipped
9,O0110,2026-01-05,2026,1,January,5,Monday,C007,Aditya Verma,Pune,...,P005,Power Bank,Electronics,VoltPlus,1199,1,1199,Low,UPI,Delivered

In [85]:
# Display the final number of rows and columns
print("Final dataset shape:", processed.shape)

Final dataset shape: (120, 22)

In [ ]:
# Data Quality Check

In [86]:
# Check the number of missing values in every column
print("Missing values in each column:")
display(processed.isnull().sum())

Missing values in each column:

Order_ID                0
Order_Date              0
Order_Year              0
Order_Month             0
Order_Month_Name        0
Order_Day               0
Order_Day_Name          0
Customer_ID             0
Customer_Name           0
City                    0
Region                  0
Membership_Type         0
Product_ID              0
Product_Name            0
Category                0
Brand                   0
Unit_Price              0
Quantity                0
Total_Amount            0
Order_Value_Category    0
Payment_Method          0
Order_Status            0
dtype: int64

In [87]:
# Check whether the final dataset contains duplicate rows
print("Number of duplicate rows:", processed.duplicated().sum())

Number of duplicate rows: 0

In [88]:
# Display the earliest and latest order dates
print("Earliest order date:", processed["Order_Date"].min())
print("Latest order date:", processed["Order_Date"].max())

Earliest order date: 2026-01-01 00:00:00
Latest order date: 2026-03-30 00:00:00

In [89]:
# Define the output CSV file name
output_file = "/content/drive/MyDrive/Processed_Ecommerce_Dataset.csv"
# Export the final processed DataFrame to a CSV file
# index=False prevents Pandas from saving the DataFrame index as an extra column
processed.to_csv(
    output_file,
    index=False
)
# Confirm that the file has been created
print("Processed dataset exported successfully!")
print("File location:", output_file)

Processed dataset exported successfully!
File location: /content/drive/MyDrive/Processed_Ecommerce_Dataset.csv

In [ ]:
## Load the exported processed dataset to verify the CSV file

In [90]:
processed_check = pd.read_csv("/content/drive/MyDrive/Processed_Ecommerce_Dataset.csv")

In [91]:
# Display the first five rows of the exported dataset
display(processed_check.head())

# Display the shape of the exported dataset
print("Exported dataset shape:", processed_check.shape)

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name,Customer_ID,Customer_Name,City,...,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Total_Amount,Order_Value_Category,Payment_Method,Order_Status
0,O0051,2026-01-01,2026,1,January,1,Thursday,C008,Sara Ahmed,Hyderabad,...,P017,Yoga Mat,Sports,FitLife,899,4,3596,Medium,Net Banking,Delivered
1,O0091,2026-01-01,2026,1,January,1,Thursday,C002,Zoya Khan,Delhi,...,P011,Air Fryer,Home & Kitchen,CookSmart,4999,2,9998,High,Credit Card,Delivered
2,O0022,2026-01-02,2026,1,January,2,Friday,C023,Nikhil Sood,Chandigarh,...,P014,Data Science Handbook,Books,DataPress,899,4,3596,Medium,Net Banking,Delivered
3,O0106,2026-01-02,2026,1,January,2,Friday,C001,Aarav Sharma,Srinagar,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,1,3499,Medium,Net Banking,Delivered
4,O0076,2026-01-03,2026,1,January,3,Saturday,C019,Yusuf Dar,Srinagar,...,P015,Machine Learning Basics,Books,AIPress,999,1,999,Very low,Debit Card,Delivered

Exported dataset shape: (120, 22)